FROM node:20-alpine
RUN apk add --no-cache openssl libc6-compat dos2unix

WORKDIR /app

RUN npm i -g pnpm

COPY package.json pnpm-lock.yaml* ./
RUN sed -i '/"packageManager":/d' package.json

COPY prisma ./prisma/

RUN pnpm install --frozen-lockfile --ignore-scripts

COPY . .

RUN sed -i '/"packageManager":/d' package.json

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN pnpm prisma generate

RUN pnpm build

EXPOSE 10000
ENV PORT=10000
ENV NODE_ENV=production

COPY entrypoint.sh ./entrypoint.sh
RUN dos2unix ./entrypoint.sh && chmod +x ./entrypoint.sh

# ENTRYPOINT ["./entrypoint.sh"]
CMD ["pnpm", "start"]
